# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArGi4sOdRqUhIvLb71xIYRe5f9kkU90q
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ─────────────────────────────────────
# Load and Clean Data
# ─────────────────────────────────────

@st.cache_data
def load_data():
    url = "https://drive.google.com/uc?id=14zL5dj_UMA71tWW7VWMHxtZYk3CL_iSG"
    df = pd.read_csv(url)

    df.columns = df.columns.str.strip()
    df['Valuation ($B)'] = df['Valuation ($B)'].astype(str)
    df['Valuation ($B)'] = df['Valuation ($B)'].str.replace('[^0-9.]', '', regex=True)
    df['Valuation ($B)'] = pd.to_numeric(df['Valuation ($B)'], errors='coerce')
    df['Date Joined'] = pd.to_datetime(df['Date Joined'], errors='coerce')
    df['Year Joined'] = df['Date Joined'].dt.year
    df['Investors'] = df['Investors'].fillna('Unknown')
    return df

df = load_data()

# ─────────────────────────────────────
# Sidebar: Filter by Industry
# ─────────────────────────────────────
top_industries = df['Industry'].value_counts().head(10).index.tolist()
industry_options = ["All"] + top_industries
selected_industry = st.sidebar.selectbox("Choose an Industry", industry_options)

if selected_industry == "All":
    filtered_df = df[df['Industry'].isin(top_industries)]
else:
    filtered_df = df[df['Industry'] == selected_industry]

# ─────────────────────────────────────
# Tabs for Navigation
# ─────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["🏠 Overview", "📦 Industry Analysis", "📈 Unicorn Growth"])

# ─────────────────────────────────────
# TAB 1: Overview
# ─────────────────────────────────────
with tab1:
    st.title("🦄 Unicorn Startup Insights Dashboard")
    st.markdown("""
    Explore data on billion-dollar startups across the globe.

    **What you'll see here:**
    - 💼 Valuation distribution by industry
    - 📈 Unicorn growth by year
    - 🌍 Countries with the most unicorns
    """)

    # Graph 1 – Distribution Overview (all industries)
    st.subheader("💰 Valuation Distribution (All Industries)")

    fig, ax = plt.subplots(figsize=(10, 6))
    sns.histplot(df[df['Valuation ($B)'] < 10]['Valuation ($B)'], bins=30, kde=True, color='skyblue')
    mean_val = df['Valuation ($B)'].mean()
    median_val = df['Valuation ($B)'].median()
    plt.axvline(mean_val, color='red', linestyle='--', label=f'Mean ≈ {mean_val:.1f}B')
    plt.axvline(median_val, color='blue', linestyle='-', label=f'Median ≈ {median_val:.1f}B')
    plt.legend()
    plt.xlabel('Valuation ($B)')
    plt.ylabel('Number of Companies')
    plt.grid(True, linestyle='--', alpha=0.5)
    st.pyplot(fig)

    st.markdown("""
    - Most unicorns are valued under **$10B**
    - Only a few reach the ultra-high values ($100B+)
    """)

# ─────────────────────────────────────
# TAB 2: Industry Analysis
# ─────────────────────────────────────
with tab2:
    st.subheader(f"📦 Valuation Distribution in {selected_industry}")

    fig2, ax2 = plt.subplots(figsize=(10, 6))
    sns.boxplot(
        data=filtered_df,
        x='Industry',
        y='Valuation ($B)',
        hue='Industry',
        palette='Set2',
        showfliers=False,
        width=0.5,
        dodge=False
    )
    median_val = filtered_df['Valuation ($B)'].median()
    plt.axhline(median_val, color='red', linestyle='--', label=f'Median ≈ {median_val:.1f}B')
    plt.legend([], [], frameon=False)
    plt.xticks(rotation=30, ha='right')
    plt.grid(axis='y', linestyle='--', alpha=0.6)
    st.pyplot(fig2)

    st.markdown(f"""
    - This boxplot shows valuation spread for startups in **{selected_industry}**
    - The red dashed line marks the **median** value
    """)


    # New graph
    st.subheader("📦 Valuation Distribution by Industry (Top 10)")

    # Step 1: Filter top 10 most frequent industries
    top_industries = df['Industry'].value_counts().head(10).index
    filtered_df = df[df['Industry'].isin(top_industries)]

    # Step 2: Sort industries by median valuation
    median_order = (
        filtered_df.groupby('Industry')['Valuation ($B)']
        .median()
        .sort_values(ascending=False)
        .index
    )

    # Step 3: Create the boxplot
    fig, ax = plt.subplots(figsize=(14, 7))
    sns.boxplot(
        x='Industry',
        y='Valuation ($B)',
        data=filtered_df,
        order=median_order,
        hue='Industry',        # Added hue to match palette
        palette='Set2',
        showfliers=False,
        width=0.6,
        dodge=False            # Prevent duplicate boxes from hue
    )

    # Step 4: Add title and labels
    plt.title('How Much Are Unicorn Startups Worth?\n(Top 10 Industries)', fontsize=18, fontweight='bold')
    plt.xlabel('Industry', fontsize=14)
    plt.ylabel('Valuation in Billions of Dollars ($B)', fontsize=14)

    # Step 5: Rotate x-axis labels
    plt.xticks(rotation=30, ha='right', fontsize=12)
    plt.yticks(fontsize=12)

    # Step 6: Add grid lines
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Step 7: Annotate median values
    medians = filtered_df.groupby('Industry')['Valuation ($B)'].median().reindex(median_order)
    for i, median_val in enumerate(medians):
        plt.text(i, median_val + 1, f'{median_val:.1f}B', ha='center', fontsize=10, color='black', fontweight='bold')

    # Step 8: Final layout and render
    plt.tight_layout()
    plt.legend([],[], frameon=False)  # Hide legend
    st.pyplot(fig)

    # Text Insight
    st.markdown(f"""
    - This chart shows valuation spread by **top 10 industries**.
    - FinTech and AI show the widest ranges and highest outliers.
    - The red annotations show **median valuations**, highlighting typical company values.
    """)

# ─────────────────────────────────────
# TAB 3: Unicorn Growth and Country Stats
# ─────────────────────────────────────
with tab3:
    st.subheader("📈 Number of Unicorns Founded per Year")

    unicorns_per_year = df['Year Joined'].value_counts().sort_index()
    fig3, ax3 = plt.subplots(figsize=(10, 6))
    sns.lineplot(x=unicorns_per_year.index, y=unicorns_per_year.values, marker='o', color='teal')
    plt.xlabel("Year")
    plt.ylabel("Number of Unicorns")
    plt.grid(True, linestyle='--', alpha=0.5)
    st.pyplot(fig3)

    st.markdown("""
    - Unicorns grew rapidly post-2015
    - Major spike in **2021** during tech/VC boom
    - Slight decline visible in 2023–2024
    """)

    st.subheader("🌍 Top 10 Countries by Number of Unicorns")
    top_countries = df['Country'].value_counts().head(10)
    fig4, ax4 = plt.subplots(figsize=(10, 6))
    sns.barplot(
        x=top_countries.values,
        y=top_countries.index,
        palette='viridis'
    )
    plt.title('Top 10 Countries by Unicorn Count')
    plt.xlabel('Number of Unicorns')
    plt.ylabel('Country')
    st.pyplot(fig4)

    st.markdown("""
    - **USA** dominates with the most unicorns
    - China and India follow
    - Strong tech ecosystems drive regional growth
    """)

    st.markdown("---")
    st.markdown("""
    ## ✅ Final Conclusion

    - Most unicorns are valued under $10B, but tech giants skew the averages.
    - Fintech, AI, and SaaS have some of the highest-valued companies.
    - The unicorn boom peaked in 2021 with VC funding at its height.
    - The US continues to lead, but other nations are closing the gap.

    This dashboard gives you a snapshot of the startup world — where innovation becomes billion-dollar businesses 🚀.
    """)

# Done!
