# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xOtJOgRAFpcts7VSSg_4mkbCSA3ZOPc
"""

# app.py

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
@st.cache_data
def load_data():
    df = pd.read_csv("unicorn-startups.csv")
    df['Valuation ($B)'] = pd.to_numeric(df['Valuation ($B)'], errors='coerce')
    df['Date Joined'] = pd.to_datetime(df['Date Joined'])
    df['Year Joined'] = df['Date Joined'].dt.year
    df['Investors'] = df['Investors'].fillna("Unknown")
    return df

df = load_data()

# Title and intro
st.title("🦄 Unicorn Startups Dashboard")
st.markdown("Explore the world of billion-dollar startups by industry, country, and more.")

# Sidebar filters
industry_options = df['Industry'].value_counts().head(10).index.tolist()
selected_industry = st.sidebar.selectbox("Select an Industry", industry_options)

# Filtered data
filtered_df = df[df['Industry'] == selected_industry]

# Boxplot
st.subheader(f"Valuation Distribution in {selected_industry} Industry")
fig, ax = plt.subplots(figsize=(10, 6))
sns.boxplot(data=filtered_df, x='Industry', y='Valuation ($B)', palette='Set2', showfliers=False, width=0.5)
median_val = filtered_df['Valuation ($B)'].median()
plt.axhline(median_val, color='red', linestyle='--', label=f'Median ≈ {median_val:.1f}B')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.6)
st.pyplot(fig)

# Yearly trend
st.subheader("📈 Number of Unicorns per Year")
year_counts = df['Year Joined'].value_counts().sort_index()
fig2, ax2 = plt.subplots()
sns.lineplot(x=year_counts.index, y=year_counts.values, marker='o', color='teal')
plt.xlabel("Year")
plt.ylabel("Number of Unicorns")
plt.grid(True)
st.pyplot(fig2)

# Fun Fact or Insight
st.success(f"There are {len(filtered_df)} unicorns in the {selected_industry} industry.")

pip install streamlit
streamlit run app.py
